# Generated by Django 5.2.7 on 2025-10-08 14:04

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("day", models.DateField()),
                ("arrival", models.DateTimeField(blank=True, null=True)),
                ("departure", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-day"],
            },
        ),
    ]
