# Generated by Django 5.2.7 on 2025-10-13 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="arrival",
            new_name="check_in",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="departure",
            new_name="check_out",
        ),
    ]
