# Generated by Django 5.2.7 on 2025-10-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_rename_arrival_attendance_check_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="excuse_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for excused absence, if applicable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_excused",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the absence for this day is excused.",
            ),
        ),
    ]
