# Generated by Django 5.2.7 on 2025-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["firstname"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="credential",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "A user with that email already exists."},
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Phone number"
            ),
        ),
    ]
